### ISSUE TITLE
Qt project compilation errors with tdlib

### ISSUE THREAD

**Issue by PakitohWalls** [tdlib/td#1487]
Hi everyone!

I'm having problems compiling my Qt Project after upgrading TDLIB from version v1.3.0 to v1.7.0. 

Some of the errors displaying in QtCreator are the following:

```
 error: telegramcheckerthread.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > td::td_api::to_string<td::td_api::error>(td::tl::unique_ptr<td::td_api::error> const&)':
/usr/local/include/td/telegram/td_api.h:148: error: undefined reference to `td::td_api::to_string[abi:cxx11](td::TlObject const&)'
error: telegramcheckerthread.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > td::td_api::to_string<td::td_api::Object>(td::tl::unique_ptr<td::td_api::Object> const&)':
/usr/local/include/td/telegram/td_api.h:148: error: undefined reference to `td::td_api::to_string[abi:cxx11](td::TlObject const&)'
:-1: error: telegramcheckerthread.o: in function `td::tl::unique_ptr<td::td_api::setAuthenticationPhoneNumber> td::td_api::make_object<td::td_api::setAuthenticationPhoneNumber, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, decltype(nullptr)>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, decltype(nullptr)&&)':

```
Also there are a lot of errores displaying like this (all seem related to classes included in file lib/tdcore.a):

```
error: telegramcheckerthread.o: in function `td::td_api::error::~error()':
/usr/local/include/td/telegram/td_api.h:9196: error: undefined reference to `vtable for td::td_api::error'
 error: telegramcheckerthread.o: in function `td::td_api::setAuthenticationPhoneNumber::~setAuthenticationPhoneNumber()':
/usr/local/include/td/telegram/td_api.h:49538: error: undefined reference to `vtable for td::td_api::setAuthenticationPhoneNumber'
:-1: error: telegramcheckerthread.o: in function `td::td_api::checkDatabaseEncryptionKey::~checkDatabaseEncryptionKey()':
/usr/local/include/td/telegram/td_api.h:36339: error: undefined reference to `vtable for td::td_api::checkDatabaseEncryptionKey'
:-1: error: telegramcheckerthread.o: in function `td::td_api::tdlibParameters::~tdlibParameters()':
/usr/local/include/td/telegram/td_api.h:28084: error: undefined reference to `vtable for td::td_api::tdlibParameters'
error: /usr/local/lib/libtdcore.a(Td.cpp.o): in function `td::tl::unique_ptr<td::td_api::ok> td::make_tl_object<td::td_api::ok>()':
Td.cpp:-1: error: undefined reference to `td::td_api::ok::ok()'
```

In my machine I'm currently using

**OS:**  Linux Mint 20

**Uname -a output:** Linux paco-desktop 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linu

**Qt Version:** 5.12.5

**GCC/G++ version:** 7.5.0

**GNU ld version:** 2.34

I have tried to reinstall tdlib multiple times with no success

Additionally, in my Qt project.pro file i have configured to use C++14 for compiling

Whatever additional info needed, feel free to ask!

**Comment by levlam** [comment]
Have you linked with `tdapi` library?
