### ISSUE TITLE
building errors on tddotnet

### ISSUE THREAD

**Issue by solarin** [tdlib/td#993]
Hello everybody, 
I'm trying to build the c# solution following all the instructions.

The cmake builds succesfully many libs, then when it comes to tddotnet. i get a lot of errors like the one below.

Ideas? Any help is highly appreciated

\td\td/tl/tl_dotnet_object.h(66,9): error C2065: 'byte': undeclared identifier [\Desktop\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(66,3): error C2923: 'cli::array': 'byte' is not a valid template type argument for parameter 'Type' [\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(66,37): error C2065: 'byte': undeclared identifier [\Desktop\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(66,30): error C2923: 'cli::array': 'byte' is not a valid template type argument for parameter 'Type' [\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(66,84): error C2662: 'cli::array<Type,dimension>::array(unsigned int)': cannot convert 'this' pointer from 'cli::array' to 'cli::array<Type,dimension> %' [\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(66,84): message : Reason: cannot convert from 'cli::array' to 'cli::array<Type,dimension>' [\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(66,42): message : Conversion requires a second user-defined-conversion operator or constructor [\td\example\csharp\build64\tddotnet.vcxproj]

predefined C++ types (compiler internal)(14,1): message : see declaration of 'cli::array<Type,dimension>::array' [\Desktop\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(69,5): error C3915: 'cli::array' has no default indexed property (class indexer) [\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(87,9): error C2955: 'cli::array': use of class template requires template argument list [\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(87,36): error C2955: 'cli::array': use of class template requires template argument list [\td\example\csharp\build64\tddotnet.vcxproj]

\td\td/tl/tl_dotnet_object.h(87,81): error C2662: 'cli::array<Type,dimension>::array(unsigned int)': cannot convert 'this' pointer from 'cli::array' to 'cli::array<Type,dimension> %' [\td\example\csharp\build64\tddotnet.vcxproj]

**Comment by solarin** [comment]
update: i replaced byte with BYTE in 3 files and it compiled succesfully:

TdDotNetApi.h
TdDotNetApi.cpp
tl_dotnet_object.h

is it possible that it's just a case problem or i am missing something?

**Comment by levlam** [comment]
Thanks for the report.
This was an issue with .NET binding introduced in the commit https://github.com/tdlib/td/commit/9d1e3ed66192b9265142b36c9e6d7cacfc107b21. Your fix is right. The issue has just been fixed in the commit https://github.com/tdlib/td/commit/af61f0c7c42907e8e303fd0ad0506598aaa40a90.
